class ThaiProvinceMap {
  static const Map<String, String> englishToThai = {
    'Krung Thep Maha Nakhon': 'กรุงเทพมหานคร',
    'Samut Prakan': 'สมุทรปราการ',
    'Nonthaburi': 'นนทบุรี',
    'Pathum Thani': 'ปทุมธานี',
    'Phra Nakhon Si Ayutthaya': 'พระนครศรีอยุธยา',
    'Ang Thong': 'อ่างทอง',
    'Lop Buri': 'ลพบุรี',
    'Sing Buri': 'สิงห์บุรี',
    'Chai Nat': 'ชัยนาท',
    'Saraburi': 'สระบุรี',
    'Chon Buri': 'ชลบุรี',
    'Rayong': 'ระยอง',
    'Chanthaburi': 'จันทบุรี',
    'Trat': 'ตราด',
    'Chachoengsao': 'ฉะเชิงเทรา',
    'Prachinburi': 'ปราจีนบุรี',
    'Nakhon Nayok': 'นครนายก',
    'Sa Kaeo': 'สระแก้ว',
    'Nakhon Ratchasima': 'นครราชสีมา',
    'Buriram': 'บุรีรัมย์',
    'Surin': 'สุรินทร์',
    'Si Sa Ket': 'ศรีสะเกษ',
    'Ubon Ratchathani': 'อุบลราชธานี',
    'Yasothon': 'ยโสธร',
    'Chaiyaphum': 'ชัยภูมิ',
    'Amnat Charoen': 'อำนาจเจริญ',
    'Nong Bua Lam Phu': 'หนองบัวลำภู',
    'Khon Kaen': 'ขอนแก่น',
    'Udon Thani': 'อุดรธานี',
    'Loei': 'เลย',
    'Nong Khai': 'หนองคาย',
    'Maha Sarakham': 'มหาสารคาม',
    'Roi Et': 'ร้อยเอ็ด',
    'Kalasin': 'กาฬสินธุ์',
    'Sakon Nakhon': 'สกลนคร',
    'Nakhon Phanom': 'นครพนม',
    'Mukdahan': 'มุกดาหาร',
    'Chiang Rai': 'เชียงราย',
    'Nan': 'น่าน',
    'Phayao': 'พะเยา',
    'Phrae': 'แพร่',
    'Mae Hong Son': 'แม่ฮ่องสอน',
    'Lampang': 'ลำปาง',
    'Lamphun': 'ลำพูน',
    'Chiang Mai': 'เชียงใหม่',
    'Tak': 'ตาก',
    'Sukhothai': 'สุโขทัย',
    'Phitsanulok': 'พิษณุโลก',
    'Phichit': 'พิจิตร',
    'Phetchabun': 'เพชรบูรณ์',
    'Uthai Thani': 'อุทัยธานี',
    'Kamphaeng Phet': 'กำแพงเพชร',
    'Nakhon Sawan': 'นครสวรรค์',
    'Suphan Buri': 'สุพรรณบุรี',
    'Kanchanaburi': 'กาญจนบุรี',
    'Ratchaburi': 'ราชบุรี',
    'Nakhon Pathom': 'นครปฐม',
    'Samut Sakhon': 'สมุทรสาคร',
    'Samut Songkhram': 'สมุทรสงคราม',
    'Phetchaburi': 'เพชรบุรี',
    'Prachuap Khiri Khan': 'ประจวบคีรีขันธ์',
    'Chumphon': 'ชุมพร',
    'Ranong': 'ระนอง',
    'Surat Thani': 'สุราษฎร์ธานี',
    'Phangnga': 'พังงา',
    'Phuket': 'ภูเก็ต',
    'Krabi': 'กระบี่',
    'Trang': 'ตรัง',
    'Satun': 'สตูล',
    'Songkhla': 'สงขลา',
    'Pattani': 'ปัตตานี',
    'Yala': 'ยะลา',
    'Narathiwat': 'นราธิวาส',
    'Phatthalung': 'พัทลุง',
    'Nakhon Si Thammarat': 'นครศรีธรรมราช',
    'Bueng Kan': 'บึงกาฬ',
    'Uttaradit': 'อุตรดิตถ์',
  };

  static String localizedAdminArea(String? engName) {
    if (engName == null || engName.isEmpty) return '';
    return englishToThai[engName] ?? engName;
  }
}
